---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: "Include ansible-role-unifi-controller"
      include_role:
        name: "ansible-role-unifi-controller"
