---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
  - name: Example assertion
    assert:
      that: true
